{{- if .Values.ingress.enabled -}}
{{- $name := include "app.fullname"  . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - pathType: Prefix
            path: {{ . | quote }}
            backend:
              service:
                name: {{ $name }}-flask
                port:
                  number: 5000
        {{- end }}
  {{- end }}
{{- end }}
