replicas: 1
image:
  name: repo/flask-counter
  tag: "1.0"
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

# Configuracion autoescalado
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Configuración ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: flask-helm.test.local
      paths:
      - "/"

redis:
  cluster:
    enabled: false
  metrics:
    enabled: true
